# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
    ]
