# Generated by Django 2.0.2 on 2018-02-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20180211_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='firs_name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='last_name',
            new_name='Last_name',
        ),
    ]
