# Generated by Django 2.0.2 on 2018-02-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20180211_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='First_name',
            field=models.CharField(max_length=100),
        ),
    ]
