# Generated by Django 2.0.2 on 2018-02-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_auto_20180211_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
