# Generated by Django 2.0.2 on 2018-02-12 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('myuser', '0006_auto_20180211_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Age',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='Year',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4rth', '4rth')], default=True, max_length=6),
        ),
        migrations.AddField(
            model_name='myuser',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=True, max_length=6),
        ),
    ]
