# Generated by Django 2.0.2 on 2018-02-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0007_auto_20180212_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Student_profile',
            field=models.ImageField(default=1, upload_to='static/media'),
            preserve_default=False,
        ),
    ]
