# Generated by Django 2.0.2 on 2018-02-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_myuser_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ASCEND',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='CBA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='CITE',
            field=models.BooleanField(default=False),
        ),
    ]
