# Generated by Django 2.0.2 on 2018-02-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0009_auto_20180213_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='ASCEND',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='CBA',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='CITE',
        ),
    ]
