# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0010_auto_20180213_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Faculty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Student',
            field=models.BooleanField(default=False),
        ),
    ]
