# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0012_auto_20180223_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_faculty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
