# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0013_auto_20180223_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
