# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0014_auto_20180225_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='MI',
            field=models.CharField(max_length=200),
        ),
    ]
