# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0015_auto_20180303_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
