# Generated by Django 2.0.2 on 2018-02-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.IntegerField(null=True)),
                ('performance', models.IntegerField(null=True)),
                ('exam', models.IntegerField(null=True)),
                ('trinal', models.BooleanField(default=False)),
                ('midterm', models.BooleanField(default=False)),
                ('Final', models.BooleanField(default=False)),
            ],
        ),
    ]
