# Generated by Django 2.0.2 on 2018-02-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_auto_20180210_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
    ]
