# Generated by Django 2.0.2 on 2018-02-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_remove_grade_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
