# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_grade_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='First_year_Grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='Fourth_year_Grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='Second_year_Grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='Third_year_Grade',
            field=models.BooleanField(default=False),
        ),
    ]
