# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_grade_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
    ]
