# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0006_auto_20180313_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='slug',
        ),
        migrations.AddField(
            model_name='grade',
            name='First_Sem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='Second_Sem',
            field=models.BooleanField(default=False),
        ),
    ]
