# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0007_auto_20180313_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Grade', to='course.Course'),
            preserve_default=False,
        ),
    ]
