# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0008_auto_20180313_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Grade', to=settings.AUTH_USER_MODEL),
        ),
    ]
